#!/bin/bash
# DHCP Server Configuration using dnsmasq
# Provides DHCP services for Legion, Book, and IoT networks

set -e

echo "========================================"
echo "DHCP Server Configuration (dnsmasq)"
echo "========================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Please run as root (sudo)"
    exit 1
fi

# Install dnsmasq
echo "[1/3] Installing dnsmasq..."
apt-get update -qq
apt-get install -y dnsmasq

# Backup original config
echo "[2/3] Backing up original configuration..."
cp /etc/dnsmasq.conf /etc/dnsmasq.conf.backup-$(date +%Y%m%d-%H%M%S)

# Create new configuration
echo "[3/3] Creating DHCP configuration..."

cat > /etc/dnsmasq.conf << 'EOF'
# dnsmasq configuration for Zimaboard HomeLab
# Generated by dhcp-server-config.sh

# ============================================================================
# GENERAL SETTINGS
# ============================================================================

# Don't read /etc/resolv.conf for upstream DNS servers
no-resolv

# Don't read /etc/hosts
no-hosts

# Add local-only domains
local=/homelab.lan/
domain=homelab.lan

# Expand simple names (add .homelab.lan)
expand-hosts

# Upstream DNS servers (Cloudflare, Google)
server=1.1.1.1
server=1.0.0.1
server=8.8.8.8
server=8.8.4.4

# Cache size (10000 entries)
cache-size=10000

# Don't forward plain names (without dots)
domain-needed

# Don't forward addresses in the non-routed address spaces
bogus-priv

# ============================================================================
# DHCP SETTINGS FOR LEGION NETWORK (vmbr2 / 192.168.10.0/24)
# ============================================================================

# Enable DHCP on vmbr2
interface=vmbr2

# DHCP range for Legion network
dhcp-range=interface:vmbr2,192.168.10.100,192.168.10.200,24h

# Default gateway
dhcp-option=interface:vmbr2,option:router,192.168.10.1

# DNS servers
dhcp-option=interface:vmbr2,option:dns-server,192.168.10.1

# Domain name
dhcp-option=interface:vmbr2,option:domain-name,homelab.lan

# NTP server (Zimaboard itself)
dhcp-option=interface:vmbr2,option:ntp-server,192.168.10.1

# Static IP for Legion (based on MAC address)
# Replace XX:XX:XX:XX:XX:XX with actual MAC address
# dhcp-host=XX:XX:XX:XX:XX:XX,legion,192.168.10.10,infinite

# ============================================================================
# DHCP SETTINGS FOR BOOK NETWORK (vmbr3 / 192.168.20.0/24)
# ============================================================================

# Enable DHCP on vmbr3
interface=vmbr3

# DHCP range for Book network
dhcp-range=interface:vmbr3,192.168.20.100,192.168.20.200,24h

# Default gateway
dhcp-option=interface:vmbr3,option:router,192.168.20.1

# DNS servers
dhcp-option=interface:vmbr3,option:dns-server,192.168.20.1

# Domain name
dhcp-option=interface:vmbr3,option:domain-name,homelab.lan

# NTP server
dhcp-option=interface:vmbr3,option:ntp-server,192.168.20.1

# Static IP for Book
# dhcp-host=YY:YY:YY:YY:YY:YY,book,192.168.20.10,infinite

# ============================================================================
# DHCP SETTINGS FOR IOT NETWORK (vmbr4 / 192.168.30.0/24)
# ============================================================================

# Enable DHCP on vmbr4
interface=vmbr4

# DHCP range for IoT network
dhcp-range=interface:vmbr4,192.168.30.100,192.168.30.200,24h

# Default gateway
dhcp-option=interface:vmbr4,option:router,192.168.30.1

# DNS servers
dhcp-option=interface:vmbr4,option:dns-server,192.168.30.1

# Domain name
dhcp-option=interface:vmbr4,option:domain-name,homelab.lan

# NTP server
dhcp-option=interface:vmbr4,option:ntp-server,192.168.30.1

# Static IP for Sonos Beam
# dhcp-host=ZZ:ZZ:ZZ:ZZ:ZZ:ZZ,sonos-beam,192.168.30.10,infinite

# ============================================================================
# LOGGING
# ============================================================================

# Log DHCP transactions
log-dhcp

# Log to specific file
log-facility=/var/log/dnsmasq.log

# Log queries
# log-queries

# ============================================================================
# SECURITY
# ============================================================================

# Don't provide DHCP on management network (already has Slate router)
no-dhcp-interface=vmbr0
no-dhcp-interface=vmbr1
no-dhcp-interface=vmbr_monitor

# Ignore unknown clients on IoT network (whitelist-only for security)
# Uncomment to enable:
# dhcp-ignore=tag:!known,interface:vmbr4

# ============================================================================
# DNS RECORDS (OPTIONAL)
# ============================================================================

# Static DNS entries for key services
address=/proxmox.homelab.lan/192.168.8.21
address=/jellyfin.homelab.lan/192.168.8.40
address=/homeassistant.homelab.lan/192.168.8.60
address=/paperless.homelab.lan/192.168.8.50
address=/silverbullet.homelab.lan/192.168.8.50
address=/nas.homelab.lan/192.168.8.70
address=/grafana.homelab.lan/192.168.8.60
address=/ntopng.homelab.lan/192.168.8.31

# Wildcard for Proxmox containers
# address=/.lxc.homelab.lan/192.168.8.1

EOF

# Create log file
touch /var/log/dnsmasq.log
chown dnsmasq:nogroup /var/log/dnsmasq.log

# Create hosts file with static entries
cat > /etc/dnsmasq.hosts << 'EOF'
# Static host entries for Zimaboard HomeLab
192.168.8.21    proxmox pve
192.168.8.30    suricata ids
192.168.8.31    ntopng monitor
192.168.8.32    deskflow kvm
192.168.8.33    pipewire audio
192.168.8.40    jellyfin media docker-media
192.168.8.50    paperless silverbullet docker-knowledge
192.168.8.60    homeassistant hass docker-iot
192.168.8.70    nas openmediavault omv
192.168.8.80    nessus scanner
EOF

# Add hosts file to dnsmasq
echo "addn-hosts=/etc/dnsmasq.hosts" >> /etc/dnsmasq.conf

# Test configuration
echo ""
echo "Testing dnsmasq configuration..."
dnsmasq --test

# Restart dnsmasq
echo "Restarting dnsmasq service..."
systemctl restart dnsmasq
systemctl enable dnsmasq

# Show status
echo ""
echo "========================================"
echo "DHCP server configuration complete!"
echo "========================================"
echo ""
echo "Summary:"
echo "  ✓ dnsmasq installed and configured"
echo "  ✓ DHCP enabled for:"
echo "    - vmbr2 (Legion): 192.168.10.100-200"
echo "    - vmbr3 (Book):   192.168.20.100-200"
echo "    - vmbr4 (IoT):    192.168.30.100-200"
echo "  ✓ DNS resolver configured"
echo "  ✓ Static DNS entries created"
echo ""
echo "Service status:"
systemctl status dnsmasq --no-pager -l
echo ""
echo "IMPORTANT: Configure static DHCP reservations"
echo "Edit /etc/dnsmasq.conf and add MAC addresses:"
echo ""
echo "  # Find MAC address of Legion:"
echo "  tail -f /var/log/dnsmasq.log"
echo "  # (Connect Legion to network and watch for DHCP request)"
echo ""
echo "  # Then add to /etc/dnsmasq.conf:"
echo "  dhcp-host=AA:BB:CC:DD:EE:FF,legion,192.168.10.10,infinite"
echo ""
echo "View DHCP leases:"
echo "  cat /var/lib/misc/dnsmasq.leases"
echo ""
echo "Monitor DHCP activity:"
echo "  tail -f /var/log/dnsmasq.log"
echo ""
echo "Test DNS resolution:"
echo "  dig @192.168.10.1 jellyfin.homelab.lan"
echo ""
